### ISSUE TITLE
Publish tries to assign metadata to all parquets in dataset

### ISSUE THREAD

**Issue by schafrn** [IntegriChain1/s3parq#17]
## Description:
Whenever a dataframe is published into a dataset, it tries to reassign all metadata inside the matching bucket+key - this includes all the previous runs. Publish should only be touching the files its directly made that run for this functionality

**Comment by norton120** [comment]
@schafrn did we fix this in the last release?

**Comment by schafrn** [comment]
@norton120 That release did not fix this particular issue - that release fixed that all columns datatypes were being set in the metadata instead of just the partitions datatypes.
